config/routes.rb
Rails.application.routes.draw do

  root to: 'whiskeys#index'

  resources :countries
  resources :grades
  resources :whiskeys do
    resources :grades
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/grade.rb
class Grade < ApplicationRecord
  SCALE = 1..10

  belongs_to :whiskey
  attr_accessor :name, :description

  validates :taste, :color, :smokiness, numericality: {
    greater_than_or_equal_to: SCALE.first, less_than_or_equal_to: SCALE.last, only_integer: true
  }

  scope :with_min_taste_score, ->(score) { where('taste >= ?', score) }
  scope :with_min_color_score, ->(score) { where('color >= ?', score) }
  scope :with_min_smokiness_score, ->(score) { where('smokiness >= ?', score) }
  scope :with_whiskey_name, ->(term) { joins(:whiskey).merge(Whiskey.with_name(term)) }
  scope :with_whiskey_description, ->(term) { joins(:whiskey).merge(Whiskey.with_description(term)) }

end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @filter = GradesFilter.new(filter_params)
    @grades = @filter.apply
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new(whiskey_id: params[:whiskey_id])
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to grades_path, notice: "Grade was successfully created." }
        format.json { render :show, status: :created, location: grades_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: "Grade was successfully updated." }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: "Grade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grade_params
      params.fetch(:grade, {}).permit(:name, :description, :whiskey_id, :taste, :color, :smokiness)
    end

    def filter_params
      params.fetch(:grades_filter, {}).permit(:name, :description, :taste_score, :color_score, :smokiness_score)
    end

end

app/views/grades/_form.html.slim
= simple_form_for @grade do |f|
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    .row
      .col-8 = f.association :whiskey, label: false
      .col-1.pt-2 = 'or'
      .col-3
        = link_to 'Add new whiskey', new_whiskey_path, class: 'btn btn-outline-primary'
    .row
      .col-sm = f.input :taste, as: :select, collection: 1..10
      .col-sm = f.input :color, as: :select, collection: 1..10
      .col-sm = f.input :smokiness, as: :select, collection: 1..10

  .form-actions
    = f.submit 'Save', class: 'btn btn-primary'
    = yield

app/views/grades/_index.slim
table.table.table-sm
  thead
    tr
      th = 'Name'
      th = 'Description'
      th = 'Taste'
      th = 'Color'
      th = 'Smokiness'
      th = 'Rated on'
      th
      th

  tbody
    - @grades.each do |grade|
      tr
        td = link_to grade.whiskey.name, grade.whiskey
        td = link_to grade.whiskey.description || '', grade.whiskey
        td = grade.taste
        td = grade.color
        td = grade.smokiness
        td = l grade.created_at.to_date
        td = link_to 'Edit', edit_grade_path(grade)
        td = link_to 'Destroy', grade, data: { confirm: 'Are you sure?' }, method: :delete

br

app/views/grades/edit.html.slim
h1 Editing grade

= render 'form' do
  = link_to 'Back', grades_path, class: 'btn'

app/views/grades/index.html.slim
.jumbotron.whiskey_background
  h3 = 'Filter grades'
  = simple_form_for @filter, url: grades_path, method: :get do |f|
    .form-inputs
      .row
        .col-lg-3.col-sm-6 = f.input :name
        .col-lg-3.col-sm-6 = f.input :description
      .row
        .col-lg-3.col-sm-4 = f.input :taste_score, as: :select, collection: Grade::SCALE, label: 'Minimum taste score'
        .col-lg-3.col-sm-4 = f.input :color_score, as: :select, collection: Grade::SCALE, label: 'Minimum color score'
        .col-lg-3.col-sm-4 = f.input :smokiness_score, as: :select, collection: Grade::SCALE, label: 'Minimum smokiness score'
      .row
        .col
          = f.submit 'Apply filter', class: 'btn btn-secondary'
          .float-right = link_to 'Add new grade', new_grade_path, class: 'btn btn-primary active'
      .row.mt-2
        .col
          .float-right = link_to 'See all whiskeys', whiskeys_path, class: 'btn btn-outline-primary active'

h1 = 'Whiskey grades'

= render 'index'

app/views/grades/new.html.slim
h1 = 'Rate a whiskey'

= render 'form' do
  = link_to 'Back', grades_path, class: 'btn'

app/views/grades/show.html.slim
p#notice = notice


= link_to 'Edit', edit_grade_path(@grade)
= link_to 'Back', grades_path, class: 'btn'