config/routes.rb
Rails.application.routes.draw do

  root to: 'whiskeys#index'

  resources :countries
  resources :grades
  resources :whiskeys do
    resources :grades
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/whiskey.rb
class Whiskey < ApplicationRecord
  COST_OPTIONS = {
    '$' => 1,
    '$$' => 2,
    '$$$' => 3,
    '$$$$' => 4,
    '$$$$$' => 5,
    '$$$$$+' => 6
  }


  has_many :grades
  belongs_to :category
  belongs_to :country_of_origin, class_name: 'Country'

  validates :name, uniqueness: true
  enum cost: COST_OPTIONS

  default_scope { order(:name) }
  scope :with_name, ->(term) { where("whiskeys.name ILIKE :term", term: "%#{term}%") }
  scope :with_description, ->(term) { where("whiskeys.description ILIKE :term", term: "%#{term}%") }

end

app/controllers/whiskeys_controller.rb
class WhiskeysController < ApplicationController
  before_action :set_whiskey, only: %w[ show edit update destroy ]

  # GET /whiskeys
  # GET /whiskeys.json
  def index
    scope = Whiskey.includes(:category, :country_of_origin).page(params[:page])
    @filter = WhiskeysFilter.new(filter_params)
    @whiskeys = @filter.apply(scope)
  end

  # GET /whiskeys/1
  # GET /whiskeys/1.json
  def show
    @grades = @whiskey.grades
  end

  # GET /whiskeys/new
  def new
    @whiskey = Whiskey.new
  end

  # GET /whiskeys/1/edit
  def edit
  end

  # POST /whiskeys
  # POST /whiskeys.json
  def create
    @whiskey = Whiskey.new(whiskey_params)


    respond_to do |format|
      if @whiskey.save
        format.html { redirect_to @whiskey, notice: "Whiskey was successfully created." }
        format.json { render :show, status: :created, location: @whiskey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @whiskey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whiskeys/1
  # PATCH/PUT /whiskeys/1.json
  def update
    respond_to do |format|
      if @whiskey.update(whiskey_params)
        format.html { redirect_to @whiskey, notice: "Whiskey was successfully updated." }
        format.json { render :show, status: :ok, location: @whiskey }
        format.json { render :show, status: :ok, whiskey: @whiskey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @whiskey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /whiskeys/1
  # DELETE /whiskeys/1.json
  def destroy
    @whiskey.destroy
    respond_to do |format|
      format.html { redirect_to whiskeys_url, notice: "Whiskey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_whiskey
      @whiskey = Whiskey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def whiskey_params
      params.fetch(:whiskey, {}).permit(:name, :description, :country_of_origin_id, :category_id, :cost)
    end

    def filter_params
      params.fetch(:whiskeys_filter, {}).permit(:name, :description)
    end



end

app/helpers/whiskeys_helper.rb
module WhiskeysHelper
end

app/views/whiskeys/_form.html.slim
= simple_form_for @whiskey do |f|
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :cost, collection: Whiskey::COST_OPTIONS.keys
    = f.association :category
    = f.association :country_of_origin
  .form-actions
    = f.submit 'Create', class: 'btn btn-primary'
    = yield

app/views/whiskeys/edit.html.slim
h1 Editing whiskey

== render 'form' do
  = link_to 'Show', @whiskey, class: 'btn btn-outline-primary'
  = link_to 'Back', whiskeys_path, class: 'btn'

app/views/whiskeys/index.html.slim
.jumbotron.whiskey_background
  h3 = 'Filter whiskeys'
  = simple_form_for @filter, url: whiskeys_path, method: :get do |f|
    .form-inputs
      .row
        .col-lg-3.col-sm-6 = f.input :name
        .col-lg-3.col-sm-6 = f.input :description
      .row
        .col
          = f.submit 'Apply filter', class: 'btn btn-secondary'
          .float-right = link_to 'Add new whiskey', new_whiskey_path, class: 'btn btn-primary active'
      .row.mt-2
        .col
          .float-right = link_to 'See all grades', grades_path, class: 'btn btn-outline-primary active'

h1 = 'Listing whiskeys'

table.table.table-sm
  thead
    tr
      th = 'name'
      th = 'description'
      th = 'metacritic_score'
      th = '# metacritic score'
      th = 'cost'
      th = 'country of origin'
      th = 'category'
      th
      th
      th

  tbody
    - @whiskeys.each do |whiskey|
      tr
        td = link_to whiskey.name, whiskey
        td = whiskey.description
        td = whiskey.metacritic_score
        td = whiskey.metacritic_score_count
        td = whiskey.cost
        td = whiskey.country_of_origin&.name
        td = whiskey.category&.name
        td = link_to 'Show', whiskey
        td = link_to 'Edit', edit_whiskey_path(whiskey)
        td = link_to 'Destroy', whiskey, data: { confirm: 'Are you sure?' }, method: :delete

br
= page_entries_info @whiskeys

app/views/whiskeys/new.html.slim
h1 New whiskey

== render 'form' do
  = link_to 'Back', whiskeys_path, class: 'btn'

app/views/whiskeys/show.html.slim
p#notice = notice

h1 = @whiskey.name

table.table.table-sm
  tr
    th = 'description'
    td = @whiskey.description
  tr
    th = 'metacritic_score'
    td = @whiskey.metacritic_score
  tr
    th = 'metacritic_score_count'
    td = @whiskey.metacritic_score_count
  tr
    th = 'cost'
    td = @whiskey.cost
  tr
    th = 'country_of_origin'
    td = @whiskey.country_of_origin&.name
  tr
    th = 'category'
    td = @whiskey.category&.name

h2 = 'Grades'
- if @grades.any?
  = render '/grades/index'
- else
  p = 'Not graded yet'
= link_to 'New Grade', new_whiskey_grade_path(@whiskey), class: 'btn btn-primary'
= link_to 'Edit', edit_whiskey_path(@whiskey), class: 'btn btn-outline-primary'
= link_to 'Back', whiskeys_path, class: 'btn'