config/routes.rb
Rails.application.routes.draw do

  root to: 'whiskeys#index'

  resources :countries
  resources :grades
  resources :whiskeys do
    resources :grades
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :whiskeys

  validates :name, presence: true, uniqueness: true

  default_scope { order(:name) }
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %w[ show edit update destroy ]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.fetch(:country, {}).permit(:name)
    end
end

app/views/countries/_form.html.slim
= simple_form_for(@country) do |f|
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/countries/edit.html.slim
h1 Editing country

== render 'form'

=> link_to 'Show', @country
'|
=< link_to 'Back', countries_path

app/views/countries/index.html.slim
h1 Listing countries

table.table.table-sm
  thead
    tr
      th = 'Name'
      th
      th

  tbody
    - @countries.each do |country|
      tr
        td = link_to country.name, edit_country_path(country)
        td = link_to 'Edit', edit_country_path(country)
        td = link_to 'Destroy', country, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Country', new_country_path

app/views/countries/new.html.slim
h1 New country

== render 'form'

= link_to 'Back', countries_path

app/views/countries/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_country_path(@country)
'|
=< link_to 'Back', countries_path